import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  studySidebar: [{ type: 'autogenerated', dirName: 'study' }],
  quizSidebar: [{ type:'autogenerated',dirName:'quiz'}]

};

export default sidebars;
