name: Website deploy

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Insall dependencies
        run: pnpm i
        
      - name: Building static website
        continue-on-error: true
        run: pnpm run build

      - name: Deploying to gh-pages
        uses: actions/deploy-pages@v4.0.5
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build files
          path: build

      


